package mx.com.quadrum.entity;
// Generated 27/02/2015 06:06:06 PM by Hibernate Tools 3.6.0

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import lombok.Getter;
import lombok.Setter;
import org.springframework.format.annotation.DateTimeFormat;

/**
 * Contrato generated by hbm2java
 */
@Entity
@Table(name = "contrato", catalog = "contradosdigitales"
)
public class Contrato implements java.io.Serializable {

    @Id @GeneratedValue(strategy=IDENTITY)
    @Column(name="id", unique=true, nullable=false)
    @Getter @Setter private Integer id;
    
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "contacto", nullable = false)
    @Getter @Setter private Contacto contacto;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "estatus", nullable = false)
    @Getter @Setter private Estatus estatus;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "tipo_contrato", nullable = false)
    @Getter @Setter private TipoContrato tipoContrato;
    
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "usuario", nullable = false)
    @Getter @Setter private Usuario usuario;

    @Temporal(TemporalType.DATE)
    @DateTimeFormat(iso = DateTimeFormat.ISO.DATE)
    @Column(name = "fecha_creacion", nullable = false, length = 10)
    @Getter @Setter private Date fechaCreacion;

    @Temporal(TemporalType.DATE)
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    @Column(name = "fecha_vencimiento", nullable = false, length = 10)
    @Getter @Setter private Date fechaVencimiento;

    @Temporal(TemporalType.DATE)
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    @Column(name = "fecha_firma", nullable = false, length = 10)
    @Getter @Setter private Date fechaFirma;
    
    @Column(name = "nombre", nullable = false, length = 145)
    @Getter @Setter private String nombre;
    
    @Column(name = "visibleCliente", nullable = false)
    @Getter @Setter private Boolean visibleCliente;

    @Column(name = "rfc", length = 20)
    @Getter @Setter private String rfc;
    
    @Column(name = "monto", precision = 10)
    @Getter @Setter private BigDecimal monto;
    
    @Column(name = "sello", length = 80000)
    @Getter @Setter private String sello;
    
    @Column(name = "tieneArchivos", nullable = false)
    @Getter @Setter private Boolean tieneArchivos;
    
    @Column(name = "editable", nullable = false)
    @Getter @Setter private Boolean editable;
    
    public Contrato() {
    }

    public Contrato(Contacto contacto, Estatus estatus, TipoContrato tipoContrato, Usuario usuario, Date fechaCreacion, Date fechaVencimiento, Date fechaFirma) {
        this.contacto = contacto;
        this.estatus = estatus;
        this.tipoContrato = tipoContrato;
        this.usuario = usuario;
        this.fechaCreacion = fechaCreacion;
        this.fechaVencimiento = fechaVencimiento;
        this.fechaFirma = fechaFirma;
    }

}
