package mx.com.quadrum.entity;
// Generated 27/02/2015 06:06:06 PM by Hibernate Tools 3.6.0

import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import lombok.Getter;
import lombok.Setter;

/**
 * Contacto generated by hbm2java
 */
@Entity
@Table(name = "contacto", catalog = "contradosdigitales", uniqueConstraints = @UniqueConstraint(columnNames = "mail"))
public class Contacto implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    @Getter @Setter private Integer id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "grado")
    @Getter @Setter private Grado grado;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "empresa")
    @Getter @Setter private Empresa empresa;

    @Column(name = "nombre", nullable = false, length = 45)
    @Getter @Setter private String nombre;

    @Column(name = "paterno", nullable = false, length = 45)
    @Getter @Setter private String paterno;

    @Column(name = "materno", nullable = false, length = 45)
    @Getter @Setter private String materno;

    @Column(name = "telefono1", nullable = false, length = 45)
    @Getter @Setter private String telefono1;

    @Column(name = "telefono2")
    @Getter @Setter private String telefono2;

    @Column(name = "direccion")
    @Getter @Setter private String direccion;
    
    @Column(name = "mail", nullable = false, length = 145)
    @Getter @Setter private String mail;
    
    @Column(name = "password", length = 12)
    @Getter @Setter private String password;
    
    @Column(name = "activo", nullable = false)
    @Getter @Setter private Boolean activo;
    
    @Column(name = "primeraSesion", nullable = false)
    @Getter @Setter private Boolean primeraSesion;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "contacto")
    @Getter @Setter private List<Contrato> contratos;
    
    @Column(name = "rfc")
    @Getter @Setter private String rfc;

    public Contacto() {
    }

    public Contacto(Integer id, Grado grado, Empresa empresa, String nombre, String paterno, String materno, String telefono1, String telefono2, String direccion) {
        this.id = id;
        this.grado = grado;
        this.empresa = empresa;
        this.nombre = nombre;
        this.paterno = paterno;
        this.materno = materno;
        this.telefono1 = telefono1;
        this.telefono2 = telefono2;
        this.direccion = direccion;
    }

    public Contacto(Integer id, Grado grado, Empresa empresa, String nombre, String paterno, String materno, String telefono1, String telefono2, String direccion, List<Contrato> contratos) {
        this.id = id;
        this.grado = grado;
        this.empresa = empresa;
        this.nombre = nombre;
        this.paterno = paterno;
        this.materno = materno;
        this.telefono1 = telefono1;
        this.telefono2 = telefono2;
        this.direccion = direccion;
        this.contratos = contratos;
    }

}
