package mx.com.quadrum.entity;
// Generated 27/02/2015 06:06:06 PM by Hibernate Tools 3.6.0

import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import lombok.Getter;
import lombok.Setter;

/**
 * Empresa generated by hbm2java
 */
@Entity
@Table(name = "empresa", catalog = "contradosdigitales"
)
public class Empresa implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    @Getter @Setter private Integer id;

    @Column(name = "razon_social", nullable = false, length = 45)
    @Getter @Setter private String razonSocial;

    @Column(name = "direccion", nullable = false, length = 100)
    @Getter @Setter private String direccion;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "empresa")
    @Getter @Setter private List<Contacto> contactos;

    public Empresa() {
    }

    public Empresa(String razonSocial, String direccion) {
        this.razonSocial = razonSocial;
        this.direccion = direccion;
    }

    public Empresa(String razonSocial, String direccion, List<Contacto> contactos) {
        this.razonSocial = razonSocial;
        this.direccion = direccion;
        this.contactos = contactos;
    }

}
