package mx.com.quadrum.entity;
// Generated 27/02/2015 06:06:06 PM by Hibernate Tools 3.6.0

import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import lombok.Getter;
import lombok.Setter;

/**
 * Estatus generated by hbm2java
 */
@Entity
@Table(name = "estatus", catalog = "contradosdigitales"
)
public class Estatus implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    @Getter @Setter private Integer id;

    @Column(name = "nombre", nullable = false, length = 45)
    @Getter @Setter private String nombre;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "estatus")
    @Getter @Setter private List<Contrato> contratos;

    public Estatus() {
    }
    public Estatus(Integer id) {
        this.id = id;
    }

    public Estatus(String nombre) {
        this.nombre = nombre;
    }

    public Estatus(String nombre, List<Contrato> contratos) {
        this.nombre = nombre;
        this.contratos = contratos;
    }

}
