package mx.com.quadrum.entity;
// Generated 11/03/2015 06:26:47 PM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PermisoUsuarioId generated by hbm2java
 */
@Embeddable
public class PermisoUsuarioId  implements java.io.Serializable {


     private int permiso;
     private int usuario;

    public PermisoUsuarioId() {
    }

    public PermisoUsuarioId(int permiso, int usuario) {
       this.permiso = permiso;
       this.usuario = usuario;
    }
   


    @Column(name="permiso", nullable=false)
    public int getPermiso() {
        return this.permiso;
    }
    
    public void setPermiso(int permiso) {
        this.permiso = permiso;
    }


    @Column(name="usuario", nullable=false)
    public int getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(int usuario) {
        this.usuario = usuario;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PermisoUsuarioId) ) return false;
		 PermisoUsuarioId castOther = ( PermisoUsuarioId ) other; 
         
		 return (this.getPermiso()==castOther.getPermiso())
 && (this.getUsuario()==castOther.getUsuario());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getPermiso();
         result = 37 * result + this.getUsuario();
         return result;
   }   


}


