package mx.com.quadrum.entity;
// Generated 27/02/2015 06:06:06 PM by Hibernate Tools 3.6.0

import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import lombok.Getter;
import lombok.Setter;

/**
 * Permiso generated by hbm2java
 */
@Entity
@Table(name = "permiso", catalog = "contradosdigitales")
public class Permiso implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    @Getter @Setter private Integer id;

    @Column(name = "nombre", nullable = false, length = 45)
    @Getter @Setter private String nombre;

    @Column(name = "url", nullable = false, length = 45)
    @Getter @Setter private String url;

    @Column(name = "descripcion", length = 200)
    @Getter @Setter private String descripcion;

    @OneToMany(fetch=FetchType.LAZY, mappedBy="permiso")
    @Getter @Setter private List<PermisoUsuario> permisoUsuarios;

    public Permiso() {
    }

    public Permiso(String nombre, String url) {
        this.nombre = nombre;
        this.url = url;
    }

    public Permiso(String nombre, String url, String descripcion, List<PermisoUsuario> permisoUsuarios) {
        this.nombre = nombre;
        this.url = url;
        this.descripcion = descripcion;
        this.permisoUsuarios = permisoUsuarios;
    }

}
