package mx.com.quadrum.entity;
// Generated 27/02/2015 06:06:06 PM by Hibernate Tools 3.6.0

import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import lombok.Getter;
import lombok.Setter;

/**
 * TipoContrato generated by hbm2java
 */
@Entity
@Table(name = "tipo_contrato", catalog = "contradosdigitales"
)
public class TipoContrato implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    @Getter @Setter private Integer id;

    @Column(name = "nombre", nullable = false, length = 85)
    @Getter @Setter private String nombre;
    
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoContrato")
    @Getter @Setter private List<Contrato> contratos;

    public TipoContrato() {
    }

    public TipoContrato(String nombre, String jasper) {
        this.nombre = nombre;
    }

    public TipoContrato(String nombre, String jasper, List<Contrato> contratos) {
        this.nombre = nombre;
        this.contratos = contratos;
    }

}
