package mx.com.quadrum.entity;
// Generated 27/02/2015 06:06:06 PM by Hibernate Tools 3.6.0

import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import lombok.Getter;
import lombok.Setter;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario", catalog = "contradosdigitales", uniqueConstraints = @UniqueConstraint(columnNames = "mail")
)
public class Usuario implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    @Getter @Setter private Integer id;

    @Column(name = "nombres", nullable = false, length = 45)
    @Getter @Setter private String nombres;

    @Column(name = "paterno", nullable = false, length = 45)
    @Getter @Setter private String paterno;

    @Column(name = "materno", nullable = false, length = 45)
    @Getter @Setter private String materno;

    @Column(name = "estado", nullable = false)
    @Getter @Setter private Boolean estado;

    @Column(name = "mail", unique = true, nullable = false, length = 45)
    @Getter @Setter private String mail;

    @Column(name = "password", length = 15)
    @Getter @Setter private String password;

    @Column(name = "log", length = 45)
    @Getter @Setter private String log;
    
    @Column(name = "esAdmin")
    @Getter @Setter private Boolean esAdmin;
    
    @Column(name = "primeraSesion", nullable = false)
    @Getter @Setter private Boolean primeraSesion;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
    @Getter @Setter private List<Contrato> contratos;

    @OneToMany(fetch=FetchType.LAZY, mappedBy="usuario")
    @Getter @Setter public List<PermisoUsuario> permisoUsuarios;

    public Usuario() {
    }

    public Usuario(String nombres, String paterno, String materno, Boolean estado, String mail, String password, String log) {
        this.nombres = nombres;
        this.paterno = paterno;
        this.materno = materno;
        this.estado = estado;
        this.mail = mail;
        this.password = password;
        this.log = log;
    }

    public Usuario(String nombres, String paterno, String materno, Boolean estado, String mail, String password, String log, List<Contrato> contratos, List<PermisoUsuario> permisoUsuarios) {
        this.nombres = nombres;
        this.paterno = paterno;
        this.materno = materno;
        this.estado = estado;
        this.mail = mail;
        this.password = password;
        this.log = log;
        this.contratos = contratos;
        this.permisoUsuarios = permisoUsuarios;
    }

}
